version: '3.8'

services: 
    postgresdb:
      image: postgres
      restart: unless-stopped
      env_file: ./.env
      environment:
        - POSTGRES_USER=$DB_USER
        - POSTGRES_PASSWORD=$DB_PASSWORD
        - POSTGRES_DB=$DB_NAME
      ports:
        - 5432:5432
      volumes:
        - db:/var/lib/postgres
      networks:
        - app-network
    app:
      depends_on:
        - postgresdb
      build: ./
      restart: unless-stopped
      env_file: ./.env
      ports:
        - "8080:8080"  
      expose:
        - "8080"  # Expose the port within the Docker network
      environment:
        - DB_HOST=postgresdb
        - DB_USER=$DB_USER
        - DB_PASSWORD=$DB_PASSWORD
        - DB_NAME=$DB_NAME
        - DB_PORT=5432
      stdin_open: true
      tty: true
      networks:
        - app-network

networks:
  app-network:
    driver: bridge


volumes:
  db:




